- name: Install and configure maven on all web servers
  hosts: all
  become: yes

  tasks:
  - name: Install Maven 
    apt:  
     name: "{{ packages }}"
     state: present
    vars:
     packages:
      - maven
